name: Sync with Keycloak Server

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        id: setup-java
        uses: ./.github/actions/java-setup

      - name: Config
        id: config
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Find latest Keycloak release branch
        id: latest_release
        run: |
          LATEST_RELEASE=$(git ls-remote --heads https://github.com/keycloak/keycloak.git 'release/*' | awk -F'/' '{print $NF}' | sort -V | tail -n1)
          echo "KEYCLOAK_RELEASE_BRANCH_NAME=release/$LATEST_RELEASE" >> $GITHUB_ENV

      - name: Checkout Keycloak latest release
        uses: actions/checkout@v4
        with:
          repository: keycloak/keycloak
          ref: ${{ env.KEYCLOAK_RELEASE_BRANCH_NAME }}

      - name: Build Keycloak
        id: build-keycloak
        run: |
          ./mvnw install -Pdistribution -am -pl distribution/maven-plugins/licenses-processor
          ./mvnw -pl quarkus/deployment,quarkus/dist -am -DskipTests clean install 

      - name: Checkout keycloak-client
        uses: actions/checkout@v4
        with:
          repository: graziang/keycloak-client
          ref: main

      - name: Build Keycloak client
        id: build-keycloak-client
        run: |
          mvn -B clean install dependency:resolve -Pnightly -DskipTests=true

      - name: Sync Keycloak Sources
        run: ./.github/scripts/sync-keycloak-sources.sh

      - name: Create and push new branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME="sync-with-keycloak-server-${{ env.KEYCLOAK_RELEASE_BRANCH_NAME }}-$(date +%Y%m%d%H%M%S)"
          git checkout -b $BRANCH_NAME
          git add .
          git commit -m "Sync with Keycloak server release branch ${{ env.KEYCLOAK_RELEASE_BRANCH_NAME }}" --author="${GITHUB_ACTOR} <${GITHUB_ACTOR}@users.noreply.github.com>"
          git push --set-upstream origin $BRANCH_NAME

      - name: Create Pull Request with gh CLI
        run: |
          PR_TITLE="Sync with Keycloak server ${{ env.KEYCLOAK_RELEASE_BRANCH_NAME }}-$(date +%Y%m%d%H%M%S) branch"
          PR_BODY="This PR syncs keycloak-client with the latest Keycloak release branch ${{ env.KEYCLOAK_RELEASE_BRANCH_NAME }}"
          gh pr create --base main --head "$BRANCH_NAME" --title "$PR_TITLE" --body "$PR_BODY"
