name: Sync with Keycloak Server

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Find latest release branch
        id: latest_release
        run: |
          LATEST_RELEASE=$(git ls-remote --heads https://github.com/keycloak/keycloak.git 'release/*' | awk -F'/' '{print $NF}' | sort -V | tail -n1)
          echo "branch_name=release/$LATEST_RELEASE" >> $GITHUB_ENV

      - name: Checkout Keycloak latest release
        uses: actions/checkout@v4
        with:
          repository: keycloak/keycloak
          ref: ${{ env.branch_name }}

      - name: Build Keycloak
        uses: ./.github/actions/build-keycloak

      - name: Sync Keycloak Sources
        run: ./scripts/sync-keycloak-sources.sh

      - name: Checkout keycloak-client
        uses: actions/checkout@v4
        with:
          repository: graziang/keycloak-client
          ref: main
